name: library_managment_system
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.18.2 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  mobx: 
  flutter_mobx:
  image_picker:
  path: ^1.8.2
  path_provider: ^2.0.11
  cloud_firestore: 
  firebase_core: 
  shared_preferences:
  nb_utils: 
  intl:
  google_fonts:
  fluttertoast: ^8.0.7


  firebase_auth:
  flutter_easyloading: ^3.0.5
  firebase_storage: ^11.0.7
  firebase_database:

  percent_indicator: ^4.2.2
  flutter_image_compress: ^1.1.3
  bottom_navy_bar: ^6.0.0
  auto_size_text: ^3.0.0
  fl_chart: 0.55.1
  url_launcher: ^6.1.7
  expandable: ^5.0.1
  firebase_messaging:


dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/library_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/team/
    - assets/gifs/
    - assets/other/
